In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import keras
import sklearn
import sys
import os
import random
import nltk
import requests # to send the data to the server
import json # to print the data or result to the terminal
import pickle ## to save the our trained data to the disk
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.model_selection import train_test_split

In [3]:
dataset = pd.read_csv('Salary_Data.csv')

In [4]:
print(dataset.shape)

(30, 2)


In [7]:
print(dataset[:4])

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0


In [8]:
print(dataset.columns
    )

Index(['YearsExperience', 'Salary'], dtype='object')


In [9]:
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,1].values

In [10]:
print(X.shape)

(30, 1)


In [11]:
print(Y.shape)

(30,)


In [13]:
print(Y)

[ 39343.  46205.  37731.  43525.  39891.  56642.  60150.  54445.  64445.
  57189.  63218.  55794.  56957.  57081.  61111.  67938.  66029.  83088.
  81363.  93940.  91738.  98273. 101302. 113812. 109431. 105582. 116969.
 112635. 122391. 121872.]


In [14]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.27,random_state =0)

In [16]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(21, 1)
(9, 1)
(21,)
(9,)


In [17]:
model = LinearRegression()

In [18]:
model.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [20]:
y_pred   = model.predict(X_test)

In [33]:
from sklearn.metrics import accuracy_score, mean_squared_error,mean_squared_log_error

In [26]:
print(mean_squared_error(Y_test,y_pred))

23370078.800832972


In [27]:
print(y_pred)

[ 40817.78327049 123188.08258899  65154.46261459  63282.41035735
 115699.87356004 108211.66453108 116635.89968866  64218.43648597
  76386.77615802]


In [28]:
print(Y_test)

[ 37731. 122391.  57081.  63218. 116969. 109431. 112635.  55794.  83088.]


In [29]:
logic = LogisticRegression()

In [30]:
logic.fit(X_train,Y_train)

c:\users\xrniraj\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\xrniraj\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [31]:
y_logic_pred = logic.predict(X_test)

In [32]:
print(mean_squared_error(Y_test,y_logic_pred))

1609634817.0


In [36]:
print(mean_squared_log_error(Y_test,y_pred))
print(mean_squared_log_error(Y_test,y_logic_pred))

0.005781641850744288
0.22993063402412683


In [39]:
print(y_pred)
print('tyoyoyoy')
print(y_logic_pred)
print('gigoign')
print(Y_test)

[ 40817.78327049 123188.08258899  65154.46261459  63282.41035735
 115699.87356004 108211.66453108 116635.89968866  64218.43648597
  76386.77615802]
tyoyoyoy
[ 64445. 121872. 121872. 121872. 121872. 121872. 121872. 121872. 121872.]
gigoign
[ 37731. 122391.  57081.  63218. 116969. 109431. 112635.  55794.  83088.]


In [41]:
pickle.dump(model, open('model.pkl','wb'))

In [43]:
load_same_model_of_Lregression = pickle.load(open('model.pkl','rb'))
print(load_same_model_of_Lregression.predict([[1.8]]))

[43625.86165635]
